[package]
name = "discidium"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.13"
eframe = { version = "0.29.0", features = ["persistence"] }
pollster = "0.3.0"
ratelimit = "0.9.1"
serde = { version = "1.0.210", features = ["derive"] }
ureq = { version = "2.10.1", features = [ "json" ] }
