[package]
name = "discidium"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
arboard = "3.4.1"
chrono = { version = "0.4.38", features = ["serde"] }
cushy = "0.4.0"
flate2 = "1.0.34"
keyring = { version = "3.6.1", features = [
  "apple-native",
  "windows-native",
  "linux-native-sync-persistent",
] }
parking_lot = "0.12.3"
pollster = "0.3.0"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.210", features = ["derive"] }
serde-aux = "4.5.0"
tungstenite = { version = "0.24.0", features = [
  "rustls",
  "rustls-tls-native-roots",
] }
ureq = { version = "2.10.1", features = ["json"] }
whoami = "1.5.2"
