[package]
name = "discidium"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
crossbeam-channel = "0.5.13"
eframe = { version = "0.29.0", features = ["persistence"] }
flate2 = "1.0.34"
pollster = "0.3.0"
serde = { version = "1.0.210", features = ["derive"] }
tungstenite = { version = "0.24.0", features = ["rustls", "rustls-tls-native-roots"] }
ureq = { version = "2.10.1", features = [ "json" ] }
