name: Github Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dioxus Deploy
        uses: DioxusLabs/deploy-action@4f933485ec8f37a9dc1beec181f4eba58789523e
        with:
          # dioxus-cli install repo [default: 'DioxusLabs/cli']
          toolSource: DioxusLabs/cli
          # Build projects using different modes [default: 'release']
          buildMode: release
          # Build projects using a different rust toolchain [default: 'stable']
          toolchain: stable
          # The `out_dir` property configured in Dioxus.toml [default: 'dist']
          outDirectory: dist
          # Source code root path [default: '.']
          rootPath: .
