name: Github Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write # for committing to gh-pages branch.

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: cachix/install-nix-action@v30
          with:
            nix_path: nixpkgs=channel:nixos-unstable
        - uses: DeterminateSystems/magic-nix-cache-action@v8
        - name: Build
          run: nix develop --command bash -c "trunk build --release --public-url $public_url --dist ./dist/"
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: dist
            # this option will not maintain any history of your previous pages deployment
            # set to false if you want all page build to be committed to your gh-pages branch history
            single-commit: true
